version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - nginx.cert
      - nginx.key
      - .htpasswd

  postgres:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin_db
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - 5050:80

  redis:
    image: redis:latest
    ports:
      - 10400:6379

  redis-ts:
    image: redislabs/redistimeseries
    ports:
      - 10500:6379

  redis-grpc:
    image: redis-web_main
    depends_on:
      - redis
    environment:
      - RUST_LOG=INFO
      - REDIS_GRPC_HOST=redis://redis:6379
    ports:
      - '50051:50051'

  lambda_engine:
    build:
      context: .
      dockerfile: lambda_engine.Dockerfile
    working_dir: /app
    environment:
      - ENV=development
    ports:
      - 6008:6008

  gen_js:
    build:
      context: .
      dockerfile: gen_js.Dockerfile
    working_dir: /app
    environment:
      - DIR=/app/proto
      - OUT_DIR=/app/proto/gen-js
      - PROTO_FILE=lambda_view.proto
    volumes:
      - ./proto:/app/proto

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - $PWD/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=redis-datasource

secrets:
  nginx.cert:
    file: ./cert/nginx.cert
  nginx.key:
    file: ./cert/nginx.key
  .htpasswd:
    file: ./.htpasswd