version: '3.1'

services:
  postgres:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80

  redis:
    image: redis:latest
    ports:
      - 10400:6379

  redis-ts:
    image: redislabs/redistimeseries
    ports:
      - 10500:6379

  lambda_engine:
    build:
      context: .
      dockerfile: lambda_engine.Dockerfile
    command: luban swap-mm-ethusd
    volumes:
      - ./environments:/app/environments
    environment:
      - ENV=development
    ports:
      - 6008:6008

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '10600:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=redis-datasource
volumes:
  postgres:
  pgadmin:
