name = 'swap-mm-sim'

[lambda_params]
book = 'SWAP-MM-SIM'
market_depths = [
    'ETH-PERP.SIM',
    'ETH/USD.SIM',
]

[init_params]
depth_symbol = 'ETH-PERP.SIM'
hedge_symbol = 'ETH/USD.SIM'

[strategy_params]
base_size = 0.001
min_basis = 3.5
min_level = 5
state = 'Init'
target_acc_size = 31.0
