name = 'swap-mm-ethusd'

[lambda_params]
book = 'SWAP-MM-ETH'
market_depths = [
    'ETH-PERP.FTX',
    'ETH/USD.FTX',
]

[init_params]
depth_symbol = 'ETH-PERP.FTX'
hedge_symbol = 'ETH/USD.FTX'

[strategy_params]
min_level = 5
min_basis = 3.0
base_size = 0.001
