name = 'swap-mm-ethusd'
registry = 'SwapMM'

[lambda_params]
book = 'SWAP-MM-ETH'
market_depths = [
    'ETH-PERP.FTX',
    'ETH/USD.FTX',
]

[init_params]
depth_symbol = 'ETH-PERP.FTX'
hedge_symbol = 'ETH/USD.FTX'

[strategy_params]
base_size = 0.001
min_basis = 1.0
min_level = 5
state = 'Init'
target_acc_size = 100.0
